AWSTemplateFormatVersion: "2010-09-09"

Description: High Avaibility Bank ASG

Resources:
#VPC
  BankVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags: 
        - Key: "Name" 
        Value: "Bank VPC"


#Security Group
  BankSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP & SSH access
      VpcId: !Ref BankVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: "Name" 
        Value: "Security Group Bank VPC"

# Internet Gateway
  BankInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: "Name" 
        Value: "Bank Internet Gateway"

# Attach IGW to VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref BankVPC
      InternetGatewayId: !Ref BankInternetGateway

#Subnet 1
Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LuBankVPC
      CidrBlock: 10.10.1.0/24
      AvailabilityZone: "ap-southeast-1a"
      MapPublicIpOnLaunch: yes
      Tags: 
        - Key: "Name" 
        Value: "PublicSubnet 1 Bank VPC"

#Subnet 2
Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LuBankVPC
      CidrBlock: 10.10.2.0/24
      AvailabilityZone: "ap-southeast-1b"
      MapPublicIpOnLaunch: yes
      Tags: 
        - Key: "Name" 
        Value: "PublicSubnet 1 Bank VPC"
  
# Subnet 3
  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LuBankVPC
      CidrBlock: 10.10.3.0/24
      AvailabilityZone: "ap-southeast-1c"
      MapPublicIpOnLaunch: yes
      Tags: 
        - Key: "Name" 
        Value: "PublicSubnet 1 Bank VPC"

